### PR TITLE
Update acme.sh git repo organization

### PR DESCRIPTION
**Pull request by robbyoconnor**
The repo moved so fix this

### CODE REVIEW

**Comment by nickjj** [comment]
Hi,

Thanks can you also update the location in the readme file in a few spots and force push a commit message to `Update acme.sh git repo organization`?

**Comment by robbyoconnor** [comment]
@nickjj sure thing!

**Comment by robbyoconnor** [comment]
Done.

**Comment by nickjj** [comment]
The readme file is still referencing the old repo btw.

**Comment by robbyoconnor** [comment]
Handled @nickjj

**Comment by nickjj** [comment]
Thanks, since we're here would you mind also updating this link in the readme https://github.com/acmesh-official/acme.sh#7-automatic-dns-api-integration to be https://github.com/acmesh-official/acme.sh/wiki/dnsapi?

Then it'll be good to go for a merge.

**Comment by robbyoconnor** [comment]
@nickjj handled -- double check since you referenced it a couple of lines down I switched that.

**Comment by nickjj** [comment]
Thanks!

**Pull request merged**
